server:
  port: 8080

spring:
  application:
    name: store-management

  datasource:
    url: jdbc:mysql://turntable.proxy.rlwy.net:28840/railway
    username: root
    password: "bbifrWuzfhUDuOFSuGVhxIVOUlKrBFpx"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
cloudinary:
  cloud-name: dpmptlswe
  api-key: 593827271151324
  api-secret: QyB_JC8u02WFwwixGMqFKdkz0uI
